---
abstract: 'Define simple entities stored in some places.'
author:
  - 'Masahiro Honma E<lt>hiratara@cpan.orgE<gt>'
build_requires:
  Test::More: 0.98
  Test::Requires: 0.06
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Class-Accessor-TrackDirty
no_index:
  directory:
    - inc
provides:
  Class::Accessor::TrackDirty:
    file: lib/Class/Accessor/TrackDirty.pm
    version: 0.01
requires:
  perl: 5.008001
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
